<?xml version="1.0" encoding="utf-8"?><Database Name="TopicaGCM" Class="TopicaDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-RJO6Q8N;Initial Catalog=TopicaGCM;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TopicaGCMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GCM" Member="GCMs">
    <Type Name="GCM">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GCMDeviceID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>